# Default values for kuard.

image:
  repository: gcr.io/kuar-demo/kuard-amd64
  tag: blue
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

podAnnotations: {}

imagePullSecrets: []

serviceAccount:
  create: true
  name: ""
  annotations: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: kuard.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

args: []
env: []

livenessProbe:
  enabled: true
  path: /healthy
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  path: /ready
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

serviceMonitor:
  enabled: false
  interval: 30s

